# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('client_order_ref', models.CharField(max_length=200)),
                ('date_order', models.DateTimeField()),
                ('partner_id', models.IntegerField()),
                ('amount_tax', models.FloatField()),
                ('procurement_group_id', models.IntegerField()),
                ('amount_untaxed', models.FloatField()),
                ('message_last_post', models.DateTimeField()),
                ('company_id', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('pricelist_id', models.IntegerField()),
                ('create_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('partner_invoice_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('date_confirm', models.DateField()),
                ('amount_total', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('partner_shipping_id', models.IntegerField()),
                ('order_policy', models.CharField(max_length=200)),
                ('picking_policy', models.CharField(max_length=200)),
                ('warehouse_id', models.IntegerField()),
                ('shipped', models.BooleanField()),
                ('commitment_date', models.DateTimeField()),
            ],
        ),
    ]
