# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosko', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saleorder',
            table='sale_order',
        ),
    ]
